package com.nomba.wraith.core.enums

enum class DisplayViewState {
    PAYMENTOPTIONS,
    TRANSFER,
    CARD,
    CARD_PIN,
    CARD_OTP,
    CARD_LOADING,
    TRANSFER_CONFIRMATION,
    TRANSFER_CONFIRMATION_INNER_ONE,
    TRANSFER_CONFIRMATION_INNER_TWO,
    PAYMENT_SUCCESS,
    PAYMENT_FAILTURE,
    SECURE3DS,
    GET_HELP
}